import { ThemeProvider } from "@/components/ThemeProvider";
import ThemeToggle from "@/components/ThemeToggle";
import "./globals.css";
import localfont from "next/font/local";
import { Metadata } from "next";
import Image from "next/image";
import NavBarWrapper from "@/components/NavBarWrapper";
import { AuthProvider } from "@/context/AuthContext";

const mazzard = localfont({
  src: [
    {
      path: "../public/fonts/MazzardM-Light.otf",
      weight: "400",
      style: "normal",
    },

    {
      path: "../public/fonts/MazzardM-Medium.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/MazzardM-Regular.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/MazzardM-SemiBold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-mazzard",
});

const radis = localfont({
  src: "../public/fonts/Radis-Sans.otf",
  variable: "--font-radis",
});

export const metadata: Metadata = {
  title: "Agentic Interview",
  description: "Generated by Agentic Interview",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[var(--background)]" suppressHydrationWarning>
      <body className={`${mazzard.variable} ${radis.variable} font-sans`} suppressHydrationWarning={true}>
        <ThemeProvider>
          <AuthProvider>
            <div className="absolute left-0 -top-30 -z-10 max-sm:hidden dark:block hidden">
              <Image width={700} height={700} src="/images/bg-shade.png" alt="" />
            </div>
            <div className="absolute right-0 -z-10 max-sm:hidden dark:block hidden">
              <Image
                className="bottom-0 right-0 -z-10"
                width={700}
                height={700}
                src="/images/bg-shade2.png"
                alt=""
              />
            </div>
            <NavBarWrapper />
            {children}
            <ThemeToggle />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

